#!/bin/bash

NGINX_DIR=../nginx-1.0.11
TMPDIR=/tmp/nginx

finalizar() {
    $NGINX_DIR/objs/nginx -p . -s stop
}

pushd .
cd $NGINX_DIR
make -j2
popd

rm -rf $TMPDIR
mkdir -p $TMPDIR
$NGINX_DIR/objs/nginx -p .

trap "finalizar" SIGINT SIGTERM SIGHUP

tail -f $TMPDIR/*.log


